name: Template Sync

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: OGCraftMC/Datapack-Template
          upstream_branch: main  # change if not main
          pr_branch_name_prefix: chore/template_sync
          pr_title: upstream merge template repository
          pr_labels: template_sync
          pr_commit_msg: merge template changes 
        env:
          SOURCE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request (fallback)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: merge template changes 
          title: upstream merge template repository
          body: |
            This PR was created automatically by the template sync workflow.
          branch: chore/template_sync
          delete-branch: false
          labels: template_sync
